import type { CityCode } from "./cities";

export const CITY_HIGHLIGHTS: Record<CityCode, string> = {
  "01": "Adana kebabı ve Taşköprü ile tanınır.",
  "02": "Nemrut Dağı'ndaki dev heykelleriyle öne çıkar.",
  "03": "Termal kaynakları ve kaymağıyla bilinir.",
  "04": "Ağrı Dağı'nın görkemli siluetine ev sahipliği yapar.",
  "05": "Kral Kaya Mezarları ve elmasıyla tanınır.",
  "06": "Anıtkabir ve başkent kültürüyle öne çıkar.",
  "07": "Kaleiçi ve Akdeniz kıyılarıyla bilinir.",
  "08": "Karagöl-Sahara manzaralarıyla öne çıkar.",
  "09": "Efes Antik Kenti ve inciriyle tanınır.",
  "10": "Kaz Dağları ve zeytinlikleriyle bilinir.",
  "11": "Osmanlı'nın kuruluş topraklarıyla öne çıkar.",
  "12": "Yüzen Adaları ve dağ gölleriyle tanınır.",
  "13": "Ahlat Selçuklu Meydan Mezarlığıyla bilinir.",
  "14": "Gölcük Tabiat Parkı'nın manzarasıyla öne çıkar.",
  "15": "Salda Gölü'nün beyaz kıyılarıyla tanınır.",
  "16": "Uludağ ve tarihi çarşılarıyla bilinir.",
  "17": "Troya'nın hikâyesi ve boğazıyla öne çıkar.",
  "18": "Tuz Mağarası ve kaya tuzuyla tanınır.",
  "19": "Hattuşa Antik Kenti ve leblebisiyle bilinir.",
  "20": "Pamukkale travertenleriyle öne çıkar.",
  "21": "Surları ve Hevsel Bahçeleriyle tanınır.",
  "22": "Selimiye Camii ve ciğeriyle bilinir.",
  "23": "Harput kültürü ve Kürsübaşı geleneğiyle bilinir.",
  "24": "Kemaliye'nin Taş Yolu'yla öne çıkar.",
  "25": "Palandöken kayak pistleriyle tanınır.",
  "26": "Porsuk Çayı ve lületaşıyla bilinir.",
  "27": "Zeugma mozaikleri ve baklavasıyla öne çıkar.",
  "28": "Fındık bahçeleri ve kirazıyla tanınır.",
  "29": "Karaca Mağarası'nın sarkıtlarıyla bilinir.",
  "30": "Cilo Dağları ve buzul gölleriyle öne çıkar.",
  "31": "Antakya mutfağı ve mozaikleriyle tanınır.",
  "32": "Gül bahçeleri ve lavantasıyla bilinir.",
  "33": "Kızkalesi ve narenciye bahçeleriyle öne çıkar.",
  "34": "Boğazı ve tarihi yarımadasıyla tanınır.",
  "35": "Kordonu ve Ege yaşamıyla bilinir.",
  "36": "Ani Harabeleri ve kazıyla öne çıkar.",
  "37": "Kastamonu evleri ve sarımsağıyla tanınır.",
  "38": "Erciyes Dağı ve mantısıyla bilinir.",
  "39": "İğneada Longozları ve bağlarıyla öne çıkar.",
  "40": "Cacabey Medresesi ve Neşet Ertaş kültürüyle tanınır.",
  "41": "İzmit pişmaniyesi ve körfeziyle bilinir.",
  "42": "Mevlana kültürü ve Selçuklu mirasıyla öne çıkar.",
  "43": "Çinileri ve termal kaynaklarıyla tanınır.",
  "44": "Kayısısı ve Arslantepe Höyüğüyle bilinir.",
  "45": "Mesir macunu ve Spil Dağı'yla öne çıkar.",
  "46": "Dondurması ve edebiyat geleneğiyle tanınır.",
  "47": "Taş evleri ve Dara Antik Kentiyle bilinir.",
  "48": "Ölüdeniz ve koylarıyla öne çıkar.",
  "49": "Muş Ovası ve lalesiyle tanınır.",
  "50": "Kapadokya vadileri ve peri bacalarıyla bilinir.",
  "51": "Aladağlar ve elmasıyla öne çıkar.",
  "52": "Boztepe manzarası ve fındığıyla tanınır.",
  "53": "Çay bahçeleri ve yaylalarıyla bilinir.",
  "54": "Sapanca Gölü ve doğasıyla öne çıkar.",
  "55": "Bandırma Vapuru ve sahiliyle tanınır.",
  "56": "Büryanı ve Botan Vadisiyle bilinir.",
  "57": "Tarihi cezaevi ve sakin limanıyla öne çıkar.",
  "58": "Divriği Ulu Camii ve kangalıyla tanınır.",
  "59": "Üzüm bağları ve köftesiyle bilinir.",
  "60": "Ballıca Mağarası ve yazmasıyla öne çıkar.",
  "61": "Sümela Manastırı ve yaylalarıyla tanınır.",
  "62": "Munzur Vadisi'nin doğasıyla bilinir.",
  "63": "Göbeklitepe ve Balıklıgöl ile öne çıkar.",
  "64": "Ulubey Kanyonu ve halısıyla tanınır.",
  "65": "Van Gölü ve kahvaltısıyla bilinir.",
  "66": "Çamlık Milli Parkı ve bozok kültürüyle öne çıkar.",
  "67": "Maden kültürü ve Gökgöl Mağarasıyla tanınır.",
  "68": "Ihlara Vadisi ve Sultanhanı'yla bilinir.",
  "69": "Baksı Müzesi ve Çoruh manzarasıyla öne çıkar.",
  "70": "Türkçenin ilk resmi dili mirasıyla tanınır.",
  "71": "Makine Kimya ve silah sanayisiyle bilinir.",
  "72": "Hasankeyf ve petrol tarihiyle öne çıkar.",
  "73": "Cudi Dağı ve dağlık doğasıyla tanınır.",
  "74": "Amasra'sı ve Küre Dağlarıyla bilinir.",
  "75": "Çıldır Gölü ve kış manzaralarıyla öne çıkar.",
  "76": "Ağrı Dağı etekleri ve kayısısıyla tanınır.",
  "77": "Termal kaplıcaları ve çiçekleriyle bilinir.",
  "78": "Safranbolu evleri ve safranıyla öne çıkar.",
  "79": "Zeytinlikleri ve yöresel mutfağıyla tanınır.",
  "80": "Yer fıstığı ve Karatepe Aslantaş'la bilinir.",
  "81": "Şelaleleri ve Efteni Gölü'yle öne çıkar.",
};

export function getCityHighlight(cityCode: string) {
  return CITY_HIGHLIGHTS[cityCode as CityCode] ?? "Yerel kültürü ve doğal dokusuyla öne çıkar.";
}
